version: "3.8"

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    networks:
      - proxy
      - backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`wordpress.ent-alpha.fr`)"
        - "traefik.http.routers.wordpress.entrypoints=websecure"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
        - "traefik.http.routers.wordpress.tls=true"
        - "traefik.docker.network=stackv5_proxy"
        - "traefik.http.services.wordpress.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.wordpress.loadBalancer.sticky.cookie.name=wwordpress_cookie_name"
      replicas: 5
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    volumes:
      - /mnt/data/wordpress/file:/var/www/html

  db:
    image: mariadb:jammy
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - /mnt/data/wordpress/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  traefik:
    image: "traefik:v2.10"
    volumes:
      - "/mnt/data/proxy/traefik.yml:/etc/traefik/traefik.yml"
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - socket-proxy
      - proxy
      - bridge
    depends_on:
      - socket-proxy
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager

  socket-proxy:
    image: tecnativa/docker-socket-proxy:edge
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy

  whoami:
    image: "traefik/whoami"
    networks:
      - proxy
    depends_on:
      - socket-proxy
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.ent-alpha.fr`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.tls=true"
      replicas: 10
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any

networks:
  bridge:
  proxy:
  socket-proxy:
  backend:
  