################################################################
#
# Configuration sample for Traefik v2.
#
# For Traefik v1: https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
          priority: 42

  websecure:
    http:
      tls:
        certResolver: letsEncrypt
        domains:
          - main: ent-alpha.fr
            sans: 
              - "*.ent-alpha.fr"

    address: :443
    http2:
      maxConcurrentStreams: 250
    forwardedHeaders:
      insecure: true
ping: {}
################################################################
# Traefik logs configuration
################################################################
log:
  level: DEBUG
  format: common

################################################################
# API and dashboard configuration
################################################################
api:
  insecure: true
  dashboard: true

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    swarmMode: true
    network: proxy

certificatesResolvers:
  letsEncrypt:
    acme:
      email: ttrarbach@ent-alpha.fr
      storage: /lets/cert/acme.json
      dnsChallenge:
        provider: ovh
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"